### ISSUE TITLE
目前版本代码应用于微博数据集，性能远低于报告结果

### ISSUE THREAD

**Issue by LeeSureman** [DianboWork/Graph4CNER#2]
dev f1只有50，test只有47，跑满了150个epoch，用的数据集来自https://github.com/hltcoe/golden-horse

**Comment by DianboWork** [comment]
你好，在微博数据集上，肯定会能超过我报告的结果，我曾经能跑到65左右，我会在之后将超参数列出。

**Comment by LeeSureman** [comment]
多谢回复，看了您的这篇大作，甚感精妙，给了我许多启发，十分的佩服！请问能顺便提供下另外三个数据集的超参吗？我跑的结果也不怎么行，但没weibo那么离谱。非常感谢您严谨的研究态度

**Comment by LeeSureman** [comment]
抱歉，突然发现跑你代码的数据用错了，那个仓库里的原版数据是带有分词标记的，我弄错了，我再去跑跑看，非常抱歉给你带来困扰

**Comment by DianboWork** [comment]
我跟新了bash脚本，脚本中列出了一份weiboNER的超参，这套超参的结果f值为66.84，远超我报告的结果

**Comment by LeeSureman** [comment]
麻烦您提供一下另外三个数据集的超参？我发现您更新的脚本与默认超参差的挺多

**Comment by DianboWork** [comment]
我之后会更新bash文件提供其他两个数据集的超参。

**Comment by Amoy-Ou** [comment]
> 我之后会更新bash文件提供其他两个数据集的超参。

您好！冒昧打扰，请问可以分享一下MSRA数据集的超参吗
