### ISSUE TITLE
关于训练数据

### ISSUE THREAD

**Issue by SaintLogos1234** [DianboWork/Graph4CNER#3]
我使用的是weiboNER_2nd_conll.train数据集作为训练数据，其原始数据格式是：
['科0\tO\n', '技1\tO\n', '全0\tO\n', '方1\tO\n', '位2\tO\n', '资0\tO\n', '讯1\tO\n', '智0\tO\n', '能1\tO\n', '，0\tO\n', '快0\tO\n', '捷1\tO\n', '的0\tO\n', '汽0\tO\n', '车1\tO\n', '生0\tO\n', '活1\tO\n', '需0\tO\n', '要1\tO\n', '有0\tO\n', '三1\tO\n', '屏2\tO\n', '一0\tO\n', '云1\tO\n', '爱2\tO\n', '你0\tO\n', '\n']
然后根据你提供的代码，会将其转化为：
['科0', '技0', '全0', '方0', '位0', '资0', '讯0', '智0', '能0', '，0', '快0', '捷0', '的0', '汽0', '车0', '生0', '活0', '需0', '要0', '有0', '三0', '屏0', '一0', '云0', '爱0', '你0']
但是在处理之后，gazs匹配的全部都为空，所以我想请教一下，是否在处理数据的过程中将原始数据转化为：
['科', '技', '全', '方', '位', '资', '讯', '智', '能', '，', '快', '捷', '的', '汽', '车', '生', '活', '需', '要', '有', '三', '屏', '一', '云', '爱', '你']

**Comment by DianboWork** [comment]
是的，需要去除原始数据中的数字。因为字典中没有”科0技0“，embedding也没有“科0“。

**Comment by SaintLogos1234** [comment]
好的，感谢你的回复
